"""
Game engine - orchestrates AI-first case generation.

Flow per case:
1. Try AI Generator (with ML-enhanced prompt) - PRIMARY
2. If AI fails completely → Use emergency fallback case

Every case the user sees is freshly generated by AI.
"""

from case_engine import CaseEngine
from judge_stats import JudgeStats
from ai_generator import AIGenerator
from firebase_handler import FirebaseHandler


class GameEngine:
    """Main game logic - AI-first with emergency fallback"""

    def __init__(self):
        self.ai_generator = AIGenerator()      # Primary case source
        self.case_engine = CaseEngine()        # Emergency fallback only
        self.firebase = FirebaseHandler()      # Optional persistence

        # In-memory sessions: {user_id: session_data}
        self.sessions = {}

    # ─── Session Management ──────────────────────────────────────────────────

    def start_session(self, user_id, difficulty="medium"):
        """Start a new game session"""
        self.sessions[user_id] = {
            "judge": JudgeStats(),
            "used_case_ids": [],
            "used_characters": [],
            "case_counter": 0,
            "current_case": None,
            "difficulty": difficulty,
            "ai_success_count": 0,
            "fallback_count": 0,
        }
        return self.get_session_state(user_id)

    def get_session_state(self, user_id):
        """Get current session state"""
        if user_id not in self.sessions:
            self.start_session(user_id)

        session = self.sessions[user_id]
        state = session["judge"].get_full_state()
        state["ai_success_count"] = session["ai_success_count"]
        state["fallback_count"] = session["fallback_count"]
        return state

    def reset_session(self, user_id):
        """Reset game - saves high score first"""
        if user_id in self.sessions:
            old_score = self.sessions[user_id]["judge"].score
            if self.firebase.enabled:
                self.firebase.update_high_score(user_id, old_score)

        return self.start_session(user_id)

    def set_difficulty(self, user_id, difficulty):
        """Change game difficulty (easy/medium/hard)"""
        if difficulty not in ("easy", "medium", "hard"):
            return {"error": "Invalid difficulty"}

        if user_id not in self.sessions:
            self.start_session(user_id, difficulty)
        else:
            self.sessions[user_id]["difficulty"] = difficulty

        return {"success": True, "difficulty": difficulty}

    # ─── Case Generation (AI-FIRST) ──────────────────────────────────────────

    def get_next_case(self, user_id):
        """
        Generate next case for user - AI is PRIMARY source.

        Flow:
        1. AI generator tries up to N times with ML-enhanced prompts
        2. Only falls back to local cases if AI completely fails
        """
        if user_id not in self.sessions:
            self.start_session(user_id)

        session = self.sessions[user_id]
        session["case_counter"] += 1

        # Game over check
        if session["judge"].is_game_over():
            return {
                "case": None,
                "source": None,
                "game_over": True,
                "message": session["judge"].get_game_over_reason(),
            }

        # ── PRIMARY: AI Generation ──
        case = self.ai_generator.generate_case(
            case_number=session["case_counter"],
            used_characters=session["used_characters"],
            difficulty=session["difficulty"],
        )

        source = "ai_generated"

        # ── EMERGENCY FALLBACK ──
        if not case:
            print(f"[GameEngine] AI failed for case #{session['case_counter']}, using emergency fallback")
            case = self.case_engine.get_emergency_case(
                exclude_ids=session["used_case_ids"]
            )
            source = "emergency_fallback"
            session["fallback_count"] += 1
        else:
            session["ai_success_count"] += 1

        if not case:
            return {
                "case": None,
                "source": None,
                "error": "Both AI and fallback failed",
            }

        # Track usage for variety
        session["used_case_ids"].append(case["id"])
        session["used_characters"].append(case["character"])
        session["current_case"] = case

        # Build response
        response = {
            "case": case,
            "source": source,
            "game_over": False,
            "case_number": session["case_counter"],
        }

        # Include quality score if AI-generated
        if "_quality" in case:
            response["quality_score"] = case["_quality"]

        return response

    # ─── Decision Processing ─────────────────────────────────────────────────

    def process_decision(self, user_id, choice_index):
        """Process judge's decision on current case"""
        if user_id not in self.sessions:
            return {"error": "No active session. Start a game first."}

        session = self.sessions[user_id]
        current_case = session.get("current_case")

        if not current_case:
            return {"error": "No active case. Request a case first."}

        choices = current_case.get("choices", [])
        if choice_index < 0 or choice_index >= len(choices):
            return {"error": "Invalid choice index"}

        # Apply effects
        choice = choices[choice_index]
        result = session["judge"].apply_effects(choice["effects"])

        # Build response
        response = {
            "case_id": current_case["id"],
            "character": current_case["character"],
            "choice_made": choice["text"],
            "applied_effects": choice["effects"],
            **result,
        }

        # Auto-save to Firebase
        if self.firebase.enabled:
            self.firebase.save_game_state(
                user_id,
                result["stats"],
                result["score"],
                result["cases_decided"],
            )

        # Update high score on game over
        if result["game_over"] and self.firebase.enabled:
            high_score_result = self.firebase.update_high_score(
                user_id, result["score"]
            )
            response["high_score_result"] = high_score_result

        # Clear current case
        session["current_case"] = None

        return response

    # ─── Stats ───────────────────────────────────────────────────────────────

    def get_stats(self, user_id):
        return self.get_session_state(user_id)

    def get_user_profile(self, user_id):
        if not self.firebase.enabled:
            return {"error": "Firebase not enabled"}
        return self.firebase.get_user(user_id)

    def get_leaderboard(self, limit=10):
        if not self.firebase.enabled:
            return {"error": "Firebase not enabled"}
        return self.firebase.get_leaderboard(limit)

    def get_ai_stats(self, user_id):
        """Get AI generation statistics for session"""
        if user_id not in self.sessions:
            return {"error": "No session"}

        session = self.sessions[user_id]
        total = session["ai_success_count"] + session["fallback_count"]
        ai_rate = (session["ai_success_count"] / total * 100) if total > 0 else 0

        return {
            "ai_generated": session["ai_success_count"],
            "emergency_fallback": session["fallback_count"],
            "ai_success_rate": f"{ai_rate:.1f}%",
            "total_cases": total,
        }